name: Extension Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Update manifest/package.json version
        run: |
          ./version-check.sh
          jq '.version = $ENV.VERSION' manifest.json
          jq '.version = $ENV.VERSION' package.json
          jq '.version = $ENV.VERSION | .packages."".version = $ENV.VERSION' package-lock.json
        env:
          VERSION: ${{ inputs.version }}

      - name: Add, commit, and tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Bumps Version to v$VERSION"
          git tag "v$VERSION"
        env:
          VERSION: ${{ inputs.version }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}