name: Extension Upgrade

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update manifest/package.json version
        run: |
          ./version-check.sh
          jq '.version = $ENV.VERSION' manifest.json > tmp && mv tmp manifest.json
          jq '.version = $ENV.VERSION' package.json > tmp && mv tmp package.json
          jq '.version = $ENV.VERSION | .packages."".version = $ENV.VERSION' package-lock.json > tmp && mv tmp package-lock.json
        env:
          VERSION: ${{ inputs.version }}

      - name: Create Pull Request
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b "${BRANCH_NAME}"
          git add .
          git commit -m "Bumps Version to v${VERSION}"
          git tag "v${VERSION}"
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create -B master -H "${BRANCH_NAME}" --title "Bumps Version to v${VERSION}" --body "Bumps Version to v${VERSION}"
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: version-bump/${{ inputs.version }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          same_commit: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}